spring:
  application:
    name: lv3-final-mission

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate.ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init.mode: always

  h2:
    console.enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.0.12:3306/final?characterEncoding=UTF-8&serverTimezone=UTC
    username: app
    password: "0000"

secret:
  jwt-key: regjeoigjroigji3j2io3io4h2bjasbdjaksbdkjqu3hu23hru3rhashudhausdhas
  jwt-expiration: 3600_000
  api-key: 120ad57b98b04dd5a6851a3ecf4bb996
